lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-test_logo_light.png
    - docs/images/nf-core-test_logo_light.png
    - docs/images/nf-core-test_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - CITATIONS.md
    - nextflow_schema.json
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - LICENSE
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
    - assets/multiqc_config.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-test_logo_light.png
    - docs/images/nf-core-test_logo_light.png
    - docs/images/nf-core-test_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - LICENSE
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
  nextflow_config: false
  nf_test_content: false
  readme:
    - nextflow_badge
    - nfcore_template_badge
  schema_description: false
  schema_lint: false
  schema_params: false
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Justin
  description: testing for citadel
  force: false
  is_nfcore: false
  name: test
  org: citadel-test
  outdir: .
  skip_features:
    - github_badges
    - license
    - test_config
    - nf-test
    - multiqc
    - fastqc
    - nf_schema
    - seqera_platform
    - gpu
    - gitpod
    - codespaces
    - vscode
    - citations
    - slackreport
  version: 1.0.0dev
