FROM python:3.13-slim-bookworm
COPY --from=ghcr.io/astral.sh/uv:python3.13-bookworm-slim uv/ uvx/ bin/

# Install dependencies
RUN uv add polars

WORKDIR /app

# Copy the project into the image
ADD . /app

